#!/bin/bash

if [[ ! "root" = "$(whoami)" ]] ; then
  echo -e "****\nThis script must be run as root.\n****" && exit 1
fi

function cmd-adduser() {
  user_name="$1"
  public_key="$2"
  authorizedkeys="/home/$user_name/.ssh/authorized_keys"

  echo -e "\nAdding user account: $user_name\n"

  #
  # create user account and home directory
  #
  useradd -m -s /bin/bash $user_name
  mkdir -p "/home/$user_name/.ssh"
  touch $authorizedkeys

  if [[ -n "$public_key" ]]; then

    # http download
    if [[ $public_key == *http ]]; then

      curl $public_key > $authorizedkeys
    # local file
    else

      if [ -f $public_key ]; then
        cat $public_key > $authorizedkeys
      else
        >&2 echo "$public_key does not exist"
        exit 1
      fi

    fi

  else
    echo "" > $authorizedkeys
    while read input; do
      echo $input >> $authorizedkeys
    done
  fi

  #
  # set ownership and permissions on authorized_keys
  #
  chown -R $user_name:$user_name /home/$user_name/.ssh
  chmod -R 0751 /home/$user_name/.ssh

  echo "$user_name ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
}

function cmd-update() {
  #
  # Upgrade installed packages to latest
  #
  echo -e "\nUpdating all installed packages\n"
  aptitude update
  aptitude safe-upgrade -y

  #
  # set timezone to Universal Coordinated Time
  #
  ln -sf /usr/share/zoneinfo/UTC /etc/localtime
}

function cmd-lockdown() {
  #
  # disable root login and password authentication over ssh
  #
  (cat /etc/ssh/sshd_config;echo "PermitRootLogin no") | sed 's/#PasswordAuthentication yes/PasswordAuthentication no/g' > ~/sshd_config
  chmod 0644 ~/sshd_config
  mv -f ~/sshd_config /etc/ssh/sshd_config
  service ssh restart  
}


function cmd-help() {
    cat<<EOF

Usage: nubuntu COMMAND [options]

Commands:
    update                        Update the system
    adduser                       Add a user
    lockdown                      Lockdown SSH access

EOF
}

main() {
  case "$1" in
  update)             shift; cmd-update $@;;
  adduser)            shift; cmd-adduser $@;;
  lockdown)           shift; cmd-lockdown $@;;
  *)                  cmd-help $@;;
  esac
}

main "$@"